model_list:
  - model_name: gemini-2.5-flash
    litellm_params:
      model: vertex_ai/gemini-2.5-flash
      vertex_project: "dbaas-bot"
      vertex_location: "us-central1"
      vertex_credentials: "/app/gcloud.json"